// <auto-generated />
using DbDiProva.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DbDiProva.Migrations
{
    [DbContext(typeof(IlMioDbContext))]
    [Migration("20231106170215_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.13");

            modelBuilder.Entity("DbDiProva.Model.Scuola", b =>
                {
                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<string>("Città")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Nome");

                    b.ToTable("scuole");
                });

            modelBuilder.Entity("DbDiProva.Model.Sport", b =>
                {
                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<string>("Città")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Nome");

                    b.ToTable("sport");
                });

            modelBuilder.Entity("DbDiProva.Model.Studente", b =>
                {
                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Scuola")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Sport")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Videogioco")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Nome");

                    b.ToTable("studenti");
                });

            modelBuilder.Entity("DbDiProva.Model.Videogioco", b =>
                {
                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipologia")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Nome");

                    b.ToTable("videogiochi");
                });
#pragma warning restore 612, 618
        }
    }
}
